maintainer       "apitrary"
maintainer_email "hgs@apitrary.com"
license          "All rights reserved"
description      "Installs/Configures base"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
dependes        "apt"
depends         "ntp"
depends         "iptables"
depends         "ssh"
